name: Build and run tests and example

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lua-version: ['5.1', '5.2', '5.3', '5.4', 'luajit']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua-version }}

      - uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake

      - name: Install Busted and dependencies
        run: |
          luarocks install busted
          luarocks install lua-cjson
          luarocks install luasocket

      - name: Build using luarocks
        run: luarocks make

      - name: Run tests
        run: busted

      - name: Run example
        run: lua example/example.lua

      - name: Run perf
        run: lua perf/perf.lua
