name: Mac build and test

on:
  push:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  macos-build-and-test:
    strategy:
      matrix:
        lua-version: ['5.1', '5.2', '5.3', '5.4', 'luajit']
      fail-fast: false

    uses: ./.github/workflows/common-build.yml
    with:
      os: macos-latest
      lua-version: ${{ matrix.lua-version }}
