name: Build and Upload Lua Package

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        luaVersion: ['5.1.5']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install cmake

      - name: Install dependencies (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install cmake

      - name: Build and install package
        run: |
          luarocks make

      - name: Create binary rock
        run: |
          luarocks pack oasvalidator-1.0.1-1.rockspec

      - name: Upload to LuaRocks
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          luarocks upload oasvalidator-1.0.1-1.${{ matrix.os }}.rock --api-key ${{ secrets.LUAROCKS_API_KEY }}
